name: Get Secret
on: workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.SERPAPI_API_KEY }}" > serpapi_key.txt
      - uses: actions/upload-artifact@v4
        with:
          name: serpapi-key
          path: serpapi_key.txt
